name: Cypress Pipeline

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.7.3'

      - name: Install dependencies
        run: npm install

      - name: Limpiar directorio de resultados de Allure
        run: rm -rf allure-results && mkdir -p allure-results

      - name: Ejecutar pruebas de Cypress con Allure Adapter
        run: npx cypress run --env allure=true

      - name: Listar resultados de Allure
        if: always()
        run: ls -la ./allure-results

      - name: Instalar Allure Commandline
        if: always()
        run: npm install allure-commandline --save-dev

      - name: Generar reporte Allure como HTML estático
        if: always()
        run: npx allure generate ./allure-results --clean -o ./allure-report

      - name: Listar reporte de Allure
        if: always()
        run: ls -la ./allure-report

      - name: Subir reporte Allure
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report
          path: ./allure-report