name: Cypress Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # O la versión que necesites

      - name: Install Java 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev rimraf

      - name: Install Allure
        run: |
          npm install -g allure-commandline --save-dev

      - name: Run tests and generate report
        run: |
          npm run limpiar-reporte
          npm run test